source "https://supermarket.chef.io"

metadata

cookbook 'apt'
cookbook 'apache2'
cookbook 'php', '~> 1.5.0'
cookbook 'openssl', '~> 4.2.0'
cookbook 'mysql', '6.0.31'
cookbook 'database', '~> 4.0.6'
cookbook 'mysql_chef_gem', '~> 2.0.2'
cookbook 'mysql2_chef_gem', '~> 1.0.2'
cookbook 'apache_vhosts', git: 'https://github.com/Arsey/apache_vhosts.git'

